### ISSUE TITLE
Define valid ingredients for user inputs

### ISSUE THREAD

**Issue by albche** [tranjack288/CSE-112-Project#11]
Prevent users from adding non-ingredient items to the ingredients list.

Define a database with a list of valid ingredients to check user inputs.

**Comment by tranjack288** [comment]
Potential dataset of valid ingredients based on cuisine: https://www.kaggle.com/datasets/kaggle/recipe-ingredients-dataset/data.

**Comment by albche** [comment]
> Potential dataset of valid ingredients based on cuisine: https://www.kaggle.com/datasets/kaggle/recipe-ingredients-dataset/data.

The dataset contains ingredients for categorized by different cuisines (aka Chinese, Italian, Greek, etc) so there will be many repeats. Experimenting with using a script to sort through all of those ingredients and output a file containing unique ingredients that we can more easily parse.

**Comment by albche** [comment]
Parsed file uploaded to firebase storage: https://console.firebase.google.com/u/0/project/noodle-66d8d/storage/noodle-66d8d.appspot.com/files
